CREATE TABLE rmdw_tables.dlvr_3po_ord (
    terr_cd smallint NOT NULL ENCODE raw,
    mcd_gbal_lcat_id_nu numeric(13,0) NOT NULL ENCODE zstd distkey,
    dlvr_3po_ord_id character varying(50) NOT NULL ENCODE raw COLLATE case_sensitive,
    dlvr_3po_ord_dt date NOT NULL ENCODE zstd,
    dlvr_3po_cust_id character varying(100) ENCODE zstd COLLATE case_sensitive,
    dlvr_3po_ord_ts timestamp without time zone ENCODE zstd,
    dlvr_3po_busn_dt date ENCODE raw,
    dlvr_3po_ord_stus_id smallint ENCODE zstd,
    dlvr_3po_ord_cplt_fl smallint NOT NULL ENCODE zstd,
    dlvr_3po_ord_uacp_fl smallint NOT NULL ENCODE zstd,
    dlvr_3po_ord_rfnd_fl smallint NOT NULL ENCODE zstd,
    dlvr_3po_ord_sch_fl smallint NOT NULL ENCODE zstd,
    dlvr_3po_ord_sch_ts timestamp without time zone ENCODE zstd,
    prep_tm_incr_fl smallint ENCODE zstd,
    tot_itm_cnt_qt smallint ENCODE zstd,
    tot_net_trn_am numeric(18,4) ENCODE zstd,
    tot_grss_trn_am numeric(18,4) ENCODE zstd,
    tot_tax_am numeric(18,4) ENCODE zstd,
    tot_adj_am numeric(18,4) ENCODE zstd,
    tot_tax_adj_am numeric(18,4) ENCODE zstd,
    dlvr_3po_cmsn_am numeric(18,4) ENCODE zstd,
    dlvr_3po_cmsn_pc numeric(10,4) ENCODE zstd,
    tot_rmtc_am numeric(18,4) ENCODE zstd,
    tot_tax_rmtc_am numeric(18,4) ENCODE zstd,
    dlvr_3po_ord_rfnd_am numeric(18,4) ENCODE zstd,
    curr_trip_beg_dura_mi_qt numeric(10,4) ENCODE zstd,
    curr_trip_drop_off_dura_mi_qt numeric(10,4) ENCODE zstd,
    curr_trip_end_dura_mi_qt numeric(10,4) ENCODE zstd,
    dlvr_3po_ord_accp_mi_qt numeric(10,4) ENCODE zstd,
    dlvr_3po_ord_prep_mi_qt numeric(10,4) ENCODE zstd,
    dlvr_3po_ord_tot_dura_mi_qt numeric(10,4) ENCODE zstd,
    dlvr_3po_ord_pkup_dura_mi_qt numeric(10,4) ENCODE zstd,
    prep_tm_incr_mi_qt smallint ENCODE zstd,
    rte_tm_mi_qt numeric(18,6) ENCODE zstd,
    ffll_tm_dura_mi_qt numeric(18,6) ENCODE zstd,
    dypt_id_nu smallint ENCODE zstd,
    dlvr_3po_mssg_itm_tx character varying(500) ENCODE zstd COLLATE case_sensitive,
    dlvr_3po_ord_ratg_nu numeric(10,2) ENCODE zstd,
    dlvr_3po_ord_ratg_busn_ts timestamp without time zone ENCODE zstd,
    hr_id_nu integer ENCODE zstd,
    load_dw_audt_ts timestamp without time zone NOT NULL DEFAULT ('now'::character varying)::timestamp with time zone ENCODE zstd,
    updt_dw_audt_ts timestamp without time zone NOT NULL DEFAULT ('now'::character varying)::timestamp with time zone ENCODE zstd,
    dlvr_3po_mssg_itm_typ_id smallint ENCODE zstd,
    dlvr_3po_id integer ENCODE zstd,
    tot_serv_fee_am numeric(18,4) ENCODE zstd,
    tot_smll_bskt_fee_am numeric(18,4) ENCODE zstd,
    tot_misc_fee_am numeric(18,4) ENCODE zstd,
    dlvr_3po_btch_ord_fl smallint ENCODE zstd,
    dlvr_3po_btch_ord_seq_nu smallint ENCODE zstd,
    dlvr_3po_itm_cndt_cat_na character varying(250) ENCODE zstd COLLATE case_sensitive,
    prmo_redm_fl smallint ENCODE zstd,
    prmo_disc_am numeric(18,4) ENCODE zstd,
    prmo_cd character varying(255) ENCODE zstd COLLATE case_sensitive,
    sbsp_fl smallint ENCODE zstd,
    dlvr_pkup_fl smallint ENCODE zstd,
    mc_crew_dlvr_fl smallint ENCODE zstd,
    mc_app_ogin_fl smallint ENCODE zstd,
    cust_fst_dlvr_3po_ord_fl smallint ENCODE zstd,
    cust_fst_mc_ord_fl smallint ENCODE zstd,
    vat_fl smallint ENCODE zstd,
    dlvr_fee_am numeric(18,4) ENCODE zstd,
    dlvr_3po_ord_min_ratg_nu numeric(10,2) ENCODE zstd,
    dlvr_3po_ord_max_ratg_nu numeric(10,2) ENCODE zstd,
    dlvr_3po_ord_avg_ratg_nu numeric(10,2) ENCODE zstd,
    dlvr_3po_ord_ratg_typ_cd smallint ENCODE zstd,
    dw_file_id character varying(36) DEFAULT '-1'::character varying ENCODE zstd COLLATE case_sensitive,
    tot_xpct_mrch_rfnd_am numeric(18,4) ENCODE zstd,
    tot_xpct_dlvr_3po_rfnd_am numeric(18,4) ENCODE zstd,
    curn_iso_nu smallint ENCODE zstd,
    grss_mdse_am numeric(18,4) ENCODE zstd,
    dlvr_3po_ord_accp_ts timestamp without time zone ENCODE zstd,
    dlvr_3po_curr_arrv_at_rest_ts timestamp without time zone ENCODE zstd,
    dlvr_3po_curr_dprt_from_rest_ts timestamp without time zone ENCODE zstd,
    dlvr_3po_ord_dlvd_ts timestamp without time zone ENCODE zstd,
    srce_dlvr_3po_ord_id character varying(100) ENCODE zstd COLLATE case_sensitive,
    mc_ord_ratg_nu numeric(12,2) ENCODE az64,
    vndr_ord_ratg_nu numeric(12,2) ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( dlvr_3po_busn_dt, terr_cd, dlvr_3po_ord_id );